### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by G-dH** [comment]
Thanks! If you used the pot file from the repository, can you update it (`make pot`) and if necessary, update your translation?

**Comment by Vistaus** [comment]
There seems to be nothing to update, so the pot file was already up-to-date.

**Comment by G-dH** [comment]
I have removed the translation for now due to the following errors:
```
po/nl.po:189: 'msgstr' is not a valid JavaScript format string, unlike 'msgid'. Reason: In the directive number 1, the character 'v' is not a valid conversion specifier.
po/nl.po:198: 'msgstr' is not a valid JavaScript format string, unlike 'msgid'. Reason: In the directive number 1, the character 'v' is not a valid conversion specifier.

```
I have to fix it.

**Comment by Vistaus** [comment]
I'm sorry to hear that. What could be the issue?

**Comment by G-dH** [comment]
The issue is that "%" is a control char for gettext.

**Comment by G-dH** [comment]
I've updated the problematic strings, can you please update your translation?

**Comment by Vistaus** [comment]
> I've updated the problematic strings, can you please update your translation?

Done! #8 Thanks for notifying me! 🙂

**Comment by G-dH** [comment]
Great. I've just added another option ;)

**Pull request merged**
